spring.application.name=corpia-api

spring.datasource.url=${SUPABASE_DB_URL}
spring.datasource.username=postgres.bkhnwbzcrpkyiufnvwho
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.ai.openai.chat.model=gpt-4o-mini

spring.ai.vectorstore.pgvector.initialize-schema=true

server.port=${PORT:8082}